# Header
menu:
  首页: /
  文章: /archives
  关于: /about

# Content
excerpt_link: 阅读全文
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- follow_mes
- recommend_posts
- category
- tagcloud
- archive
- recent_comments

# - official_accounts
# - recent_posts
# - tag
# - links

# Links
links:
  SegmentFault: https://segmentfault.com/

# recommend_posts
recommend_posts:
  
  我用Hexo搭建本博客的全过程: /2016/10/12/hexo-my-blog/
  

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: cunshuifengyun

# Baidu share
baidushare: true

# Baidu statistic
baidu_tongji: true

# 文章尾部声明
statement: true
statement_img: http://7xkhp9.com1.z0.glb.clouddn.com/blog/other/blog_statement_20160618_01.png

# 微信公众号展示
official_accounts_img: http://7xkhp9.com1.z0.glb.clouddn.com/weixin/qrcode_258.jpg
official_accounts_text: 订阅「石佳劼的博客」

# 关注我
follow_mes:
  我的「微信公众号」: http://oexmgkpcg.bkt.clouddn.com/weixinhao.jpg
 
  我的「GitHub」: https://github.com/cunshuifengyun
  

# 网站备案号
website_icp:
